spring:
  datasource:
    url: jdbc:mysql://220.132.15.117:3306/account_book?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rex
    password: ji3cp4su3F*+++
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update